#GOOGLE

TRANSLATE_LANGUAGE_CODE_ENGLISH = "en"
TTS_VOICE_CODE_ENGLISH = "en-US-Wavenet-D"
TTS_LANGUAGE_CODE_ENGLISH = "en-US"

TRANSLATE_LANGUAGE_CODE_FRENCH = "fr"
TTS_VOICE_CODE_FRENCH = "fr-FR-Standard-D"
TTS_LANGUAGE_CODE_FRENCH = "fr-FR"

TRANSLATE_LANGUAGE_CODE_GERMAN = "de"
TTS_VOICE_CODE_GERMAN = "de-DE-Wavenet-D"
TTS_LANGUAGE_CODE_GERMAN = "de-DE"

TRANSLATE_LANGUAGE_CODE_ROMANIAN = "ro"

#MICROSOFT
TTS_MICROSOFT_LANGUAGE_CODE_RO="ro-RO"
TTS_MICROSOFT_VOICE_CODE_RO="ro-RO-Andrei"
